name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      folder:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - run: echo "Hello" -- ${{ inputs.image_tag }}
      - run: echo "Hello" -- ${{ inputs.folder }}