name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      package:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v3

      - run: echo "Hello" -- ${{ inputs.image_tag }}
      - run: echo "Hello" -- ${{ inputs.package }}
      